### ISSUE TITLE
Adjust Readme.md

### ISSUE THREAD

**Issue by DavidBruchmann** [gitlist-php/gitlist#1]
Readme.md has to be adjusted to show the new links for downloads and any contributions.

**Comment by alehaa** [comment]
This fork is just a few minutes online and there it is ... the firs issue :D Will be done in a few seconds ;)

**Comment by alehaa** [comment]
Fixed in 3dc8401b5e9d5a2c13b1db5896755befc5793966 and 51bd7fae8221c9746a13638de18c52aa2862e6cd.
