### ISSUE TITLE
Update Travis CI configuration.

### ISSUE THREAD

**Issue by alehaa** [gitlist-php/gitlist#11]
At the moment, Travis CI just tests PHP 5.3 and 5.4. Versions up to 7.1 and HHVM should be tested, too.

**Comment by PABourdin** [comment]
With the silex2 migration, PHP testing had to be promoted to version 5.5.9 at minimum.
Nonetheless, one can easily add newer PHP versions, I guess.
See PR #12 and issue #4

**Comment by alehaa** [comment]
Not required anymore, as we're moving back to upstream (see #42). Upstream did already update the required PHP versions.
