### ISSUE TITLE
Error with Apache 2.4 - Primary script unknown

### ISSUE THREAD

**Issue by garyee** [gitlist-php/gitlist#14]
Hi,

I want to use gitlist on my Synology Diskstation.
I followed the installation instructions but ran into this fault:

```
2017-08-02T15:33:54+02:00 Server [Wed Aug 02 15:33:54.575323 2017] [proxy_fcgi:error] [pid 27803:tid 1379922976] [client 192.168.178.52:37851] AH01071: Got error 'Primary script unknown\n'
```

When I deleted the `.htaccess` I could see the repo list but when I wanted to see the files I got a 404 error.

My solution was to switch back to Apache 2.2

**Comment by E-t-z** [comment]
Still, there seems to be somekind of problem, not sure hw to fix this:

`Fatal error: Uncaught Error: Class 'GitList\Controller\TreeGraphController' not found in /volume1/web/gitlist/boot.php:12 Stack trace: #0 /volume1/web/gitlist/index.php(28): require() #1 {main} thrown in /volume1/web/gitlist/boot.php on line 12`

**Comment by E-t-z** [comment]
Got it fixed, looks like boot.php has directive:

`$app->mount('', new GitList\Controller\TreeGraphController());`

Which cannot be found, commenting it out makes things work.

**Comment by E-t-z** [comment]
You could always enable `mod_access_compat ` module on Apache 2.4 to have backwards compatibility with Apache 2.2 .htaccess access control directives. Unfortunately it is not always possible, so it would be better to fix it.

Created PR #17 with hybrid `.htaccess`.

**Comment by alehaa** [comment]
As we're moving back to upstream (see #42), this issue will be closed and further discussion should take place in klaussilveira/gitlist#733. I think there's already a PR with klaussilveira/gitlist#737.
