### ISSUE TITLE
Readme has references to the original project.

### ISSUE THREAD

**Issue by DannyvdSluijs** [gitlist-php/gitlist#2]
In the readme file there are some references to the original project created by Klaus Silveira.
On line 35 there is a reference to download from gitlist.org
> * Download GitList from [gitlist.org](http://gitlist.org/) and decompress to your `/var/www/gitlist` folder, or anywhere else you want to place GitList.

On line 86 there is a reference to the old CI
> * Stay tuned to possible bugs, suboptimal code, duplicated code, overcomplicated expressions and unused code with [PHPMD](http://ci.gitlist.org:8080/job/GitList%20\(master\)/9/pmdResult/?) in our CI server

And one could argue if we need to add more people to the list authors and contributors. Or even if Klaus is an active author/contributor. Don't want to steal his thunder, and am not aware what is possible under the license. But it would be a safe bet if people contact him he would work on the original, thus making him not a author/contributor. On the other side he made the initial version of Gitlist possible.

**Comment by alehaa** [comment]
I left `gitlist.org` in the README, as I don't own the domain. I think it might be possible to use GitHub pages for this purpose one day?

I didn't see the old CI ever to be online. I think checking GitList by Travis CI would be nice?

**Comment by alehaa** [comment]
Oh. After looking into the repository I saw that Travis CI is already activated. I will adjust the link soon.

**Comment by DannyvdSluijs** [comment]
Other references to gitlist.org can be found in
https://github.com/gitlist-php/gitlist/blame/master/INSTALL.md#L2
https://github.com/gitlist-php/gitlist/blob/master/pkg_builder/Makefile#L6
https://github.com/gitlist-php/gitlist/blob/master/pkg_builder/Makefile#L7
https://github.com/gitlist-php/gitlist/blob/master/index.php#L5
https://github.com/gitlist-php/gitlist/blob/master/themes/bootstrap3/js/networkGraph.js#L3
https://github.com/gitlist-php/gitlist/blob/master/themes/default/js/networkGraph.js#L3
https://github.com/gitlist-php/gitlist/blob/master/themes/default/twig/navigation.twig#L12
https://github.com/gitlist-php/gitlist/blob/master/themes/default/twig/navigation.twig#L14
https://github.com/gitlist-php/gitlist/blob/master/themes/default/twig/navigation.twig#L15
https://github.com/gitlist-php/gitlist/blob/master/themes/bootstrap3/twig/navigation.twig#L14
https://github.com/gitlist-php/gitlist/blob/master/themes/bootstrap3/twig/navigation.twig#L16
https://github.com/gitlist-php/gitlist/blob/master/themes/bootstrap3/twig/navigation.twig#L17

I guess we can update all the GitHub links from Klaus Silveira to these repo (gitlist-php) and any gitlist.org could be updated to the wiki pages once setup?

**Comment by alehaa** [comment]
Relating to this issue, I'm not sure about the copyright notice, stating "Klaus Silveira and contributors" as the copyright holder. I'm not an expert in licensing law, but shouldn't "the collective" of this group be added as author, too?

**Comment by alehaa** [comment]
Fixed several URLs, including the project's name in `composer.json`, to the new repository and its GitHub page in f63254b3794e406b77a4133ecf9d5ea353e81f56.
