### ISSUE TITLE
Error in Twig Template

### ISSUE THREAD

**Issue by garyee** [gitlist-php/gitlist#27]
Hi,

so I forked and build gitlist locally for development.
When I updated my fork to the newest commit (3ad4f03), I'am getting this error:

`Twig_Error_Runtime in layout.twig line 6: Neither the property "request" nor one of the methods "request()", "getrequest()"/"isrequest()" or "__call()" exist and have public access in class "GitList\Application".`

Did I do something wrong?

**Comment by PABourdin** [comment]
Hi @garyee , sorry, I was working on `master`.
Could you try again either with the restored `master`? Thank you.

We should define, if we consider "master" as stable or development branch.
@alehaa I guess your like to have "master" as stable and do development in feature branches?

**Comment by PABourdin** [comment]
@garyee Ahh, I see now you were trying the current HEAD on master.

Can you give me some quick instructions on how to build GitList into a production environment so that I can reproduce and fix the problem? Thank you!

**Comment by PABourdin** [comment]
I see now the README warns:
"Do not download a branch or tag from GitHub, unless you want to use the development version"
So "master" should be considered a development branch.
We may of course change that...

**Comment by alehaa** [comment]
> We should define, if we consider "master" as stable or development branch.
@alehaa I guess your like to have "master" as stable and do development in feature branches?

`master` is, what is currently running and tested. Features will be developed in separated branches (in forks) and send as PR back to this repo, where we will test and merge them. From time to time we will release new versions as tags. I think there will be packed versions with all dependencies, too.

**Comment by alehaa** [comment]
However, this bug seems to be a bug. ;)

**Comment by PABourdin** [comment]
It is indeed a bug. I'm on it and have now a development built up and running.
How do I reproduce the above error?

**Comment by PABourdin** [comment]
Before I fix it, we should create a test case for this problem.
How can I do this - or could someone else do it?

**Comment by garyee** [comment]
Hi, okay so I have an xampp on windows 7 running with Apache 2.4.x and php 7.1.2.
I just cloned from master HEAD and did composer install.

I did try to find the source of the problem but I'm fairly new to symfony and the dependency-injection stuff, so I did not succeed.

**Comment by PABourdin** [comment]
Sorry, I can't reproduce the issue here with PHP 5.5.9 on Linux. "ant" fully works for me.

**Comment by DannyvdSluijs** [comment]
This is probably due to the BC break overlooked. PR #36 fixes the BC break, where `request` has been replaced with `request_stack`. Looking at the original report this is related.
