### ISSUE TITLE
PatchLog broken

### ISSUE THREAD

**Issue by PABourdin** [gitlist-php/gitlist#29]
Again I start with our current master: 3ad4f03ad0bac9d4ae654351e67a42d614dc19ca
When I click "PatchLog", I always get this error message:

```
Oops! fatal: ambiguous argument 'FILENAME': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]'
```

Properly escaping `$file` this way: `git command -- "$file"` in `getCommitsLogPatch` fixes the issue.

Where can I push this fix?
Shall I create another branch (from master) or can I submit such small changes directly to master?

Thanks and best greetings!

**Comment by alehaa** [comment]
Commits can't be pushed directly to master, as GitHub's "protect branch" feature will refuse any update that hasn't been checked by Travis CI before. Fork this repository, create a new branch and send a PR with the changes to be done. I'll open a new issue in a few minutes to create a contributors guideline ;)

However, we should add several test cases to check GitList. I think some of the errors might come from recent merges.

**Comment by PABourdin** [comment]
Could you create one test case for this particular function, so that I learn how to create one myself?

PR #31 created. Thank you.

**Comment by alehaa** [comment]
Some already exist in `/tests`. Afaik that are regular PHPUnit tests.

**Comment by alehaa** [comment]
Merged #31.

**Comment by PABourdin** [comment]
For the records:
We indeed pulled in the bug with a recent merge.
The error originates from commit a67b0bdc7301f667460bd49725823255e19ee9c9
Even though there is a test case, see commit cceafa59cc5431f6067410b85571a36592cc205c this test did not catch this issue... :-/

**Comment by DannyvdSluijs** [comment]
Ill be back from holidays next monday. And plan to add more coverage on the unit tests. This should increase our Q&A and we can start working towards a release. Might it be an idea to have a Skype meeting between the three of us ? I saw we are all in the same time zone. We can set some shared goals as the three of us seem quite eager to boost gitlist.

**Comment by PABourdin** [comment]
Would be a good idea to speak, but I will be on a trip next week... don't know yet when I leave.

**Comment by alehaa** [comment]
@DannyvdSluijs sounds like a great idea, so we can discuss some general stuff etc. ;)
