### ISSUE TITLE
Test coverage should improve

### ISSUE THREAD

**Issue by DannyvdSluijs** [gitlist-php/gitlist#3]
As I'm using GitList day in and out I would prefer to increase the test level and thereby the stability of the GitList project and allowing proper testing of future releases and other PHP versions. I tried to do this for the original (See https://github.com/klaussilveira/gitlist/pull/468) but never got merged.

My approach would be to port the pending pull request to this fork, which 

1. Introduces vfsStream to mock any file system operations (seems legit as GitList extensively relies on the file system)
2. Start the use of namespaces in the test folder to mimic the sources folder
3. Introducing the specifying of the covers methods limiting the coverage information to the specified unit under test.

Before taking the effort the second time I would like to validate the approach in order to have my pull request, once done, merged within a reasonable time.

Please let me hear your thoughts.

**Comment by alehaa** [comment]
Hi @DannyvdSluijs,

I like testing with continuous integration. As long as it is compatible with phpunit, feel free to add some tests and send a PR ;) However, I've filed #4 about migrating to Silex 2 API. Does this result in any complications for testing?

**Comment by DannyvdSluijs** [comment]
@alehaa I'm quite sure it will not, and otherwise I'll find out. It will remain phpunit testing. Just wanted to outline the approach a bit more to validate before taking the effort. ;-) 
Will see if I can atlas port the make the same as in the pull mentioned earlier.

**Comment by alehaa** [comment]
Ok sounds good. Maybe you can fork his branch and reuse it? Think better testing might help to find any issues in #4 then. ;)

**Comment by alehaa** [comment]
Merged #5.
