### ISSUE TITLE
Status of this fork

### ISSUE THREAD

**Issue by camilstaps** [gitlist-php/gitlist#48]
Sorry for asking a question that has been brought up several times already, but it would be good to get some up-to-date info on this.

This repository is not up-to-date with klaussilveira/gitlist, but apparently does contain functionality that is not in there. Are there any incompatibilities that prevent the two from being merged?

I recently created two PRs. One of them (https://github.com/klaussilveira/gitlist/pull/788) is essentially a bug fix which can probably be merged there. The other (https://github.com/klaussilveira/gitlist/pull/789) adds a new feature and may be rejected for that reason. Would this repository be a good place for that PR then?

I understand that maintaining a fork like this is a lot of work. I can spend some time on bringing this repository up to date if that's how things are meant to be.

**Comment by alehaa** [comment]
At the time of creating this fork, we hadn't the chance to contribute to upstream, as nobody responded to issues and PRs. Now, we have a active community at upstream and several maintainers, so contributing can take place upstream.

That means: At the moment this fork is inactive. Some of the features will be merged upstream, when we have time to address this.

**Comment by camilstaps** [comment]
OK, thanks for the explanation. I will leave the PRs there then.
