### ISSUE TITLE
Integration of orphan forks

### ISSUE THREAD

**Issue by PABourdin** [gitlist-php/gitlist#7]
Hello,
I'm very interested having a new GitList centralized repository that will be maintained further.
See also this discussion: https://github.com/klaussilveira/gitlist/issues/725

As discussed, we like to integrate some forks with some useful features and fixes into this new organizational master branch. For this, I have quickly looked through existing forks and identified the following as being interesting and well-written. I would propose these forks for integration in this order:

1) ~~DannyvdSluijs/master~~ *[Edit: merged #5]*
~~=> fixes a dependency requirement.~~

2) ~~silecs/silecs (only the first commit of that branch)~~ *[Edit merged #24]*
~~=> added a feature to hide repositories in subdirectories.~~

3) ~~akashima/php7fixed~~ *[Edit: already done in feature/silex2]*
~~=> looks like a quick fix for a missing default value, might be PHP7-related.~~

4) ~~GEBIT/GEBIT~~ *[Edit merged #22]*
~~=> fixes problem with long tags, fixes Network/Treegraph to show not only master, added feature to show patch log for individual files.~~

I'm not sure about these:

5) ~~DannyvdSluijs/feature-docker~~ *[Edit: we do not promote 3rd party products]*
~~=> add an example for "docker" installation.~~

6) ~~akashima/htaccess~~ *[Edit: merged #21]*
~~=> checks that the rewrite rule is not applied to directories.~~

7) Micycle1975/master *[Edit: see branch "pr/upstream/693"]*
=> allows to view very large diffs.

Thanks and best greetings!

**Comment by alehaa** [comment]
Point 5 can be ~~strikethrough~~: see #6.

**Comment by PABourdin** [comment]
So let us keep point 5 out of this discussion for now.

**Comment by alehaa** [comment]
Merged 1 in #5 - 3 to go! ;)

**Comment by alehaa** [comment]
Merged all orphans except the one of @micycle1975, as this one failed in Travis CI. A recent merge with `master` is available in the `pr/upstream/693` branch, maybe you could see for the issue @micycle1975?

**Comment by Micycle1975** [comment]
Sure, will try to take a look later in the week - haven't touched this for
a while.

Cheers,

Michael

**Comment by PABourdin** [comment]
The current branch `pr/upstream/693` misses a commit that I still need to push.
See PR #25

**Comment by alehaa** [comment]
@PABourdin gave you rights to push on this branch.

**Comment by PABourdin** [comment]
I have added my final commits to branch `pr/upstream/693` and wait for @Micycle1975 to check my hint inside `commit.twig` that one should only display the "Full diff" button if it is really needed.

Thanks you all.

**Comment by PABourdin** [comment]
Klaus has merged in his master branch (now tagged v0.6.0) the following additional forks:

8. ~~Hologos/hotfix/incompatible-method-definition~~
=> already fixed with our Silex2 migration, see our PR #12 .

9. cleverer/clone-button
=> Extends clone button options. Sounds good!

10. cleverer/mobile
=> Makes theme bootstrap3 mobile friendly. Sounds good!

11. ~~stevemcgf/master~~
=> already merged in our PR #22 .

12. ~~myfreescalewebpage/master~~
=> already merged in our PR #22 .

13. cleverer/extended-hide
=> will collide with our merged PR #24 as this version implements a similar feature in a bit different way with subdirectory patterns. I think our branch uses the cleaner approach. Needs to be checked.

I would propose we also pull in what "sounds good" and leave the rest away, because we either have merged it already or we merge a similar fork. This would then lead us to the next version.

**Comment by alehaa** [comment]
Not required anymore, as we're moving back to upstream (see #42).
